-- MySQL Script generated by MySQL Workbench
-- Wed 07 Dec 2016 05:34:09 PM WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema form2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema form2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `form2` DEFAULT CHARACTER SET latin1 ;
USE `form2` ;

-- -----------------------------------------------------
-- Table `form2`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form2`.`curso` (
  `id_curso` VARCHAR(50) NOT NULL,
  `ofi_curso` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `form2`.`accao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form2`.`accao` (
  `cod_accao` VARCHAR(10) NOT NULL,
  `desc_accao` VARCHAR(50) NOT NULL,
  `fk_curso` VARCHAR(50) NOT NULL,
  `data_inicio` DATE NULL DEFAULT NULL,
  `data_fim` DATE NULL DEFAULT NULL,
  `horario` ENUM('08h-14h', '14h-20h') NULL DEFAULT NULL,
  `obs` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_accao`),
  INDEX `fk_curso` (`fk_curso` ASC),
  CONSTRAINT `accao_ibfk_1`
    FOREIGN KEY (`fk_curso`)
    REFERENCES `form2`.`curso` (`id_curso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `form2`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form2`.`pessoa` (
  `username` VARCHAR(40) NULL DEFAULT NULL,
  `password` VARCHAR(40) NULL DEFAULT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `cc` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`cc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `form2`.`formando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form2`.`formando` (
  `id_formando` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `fk_cc` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_formando`),
  INDEX `fk_cc` (`fk_cc` ASC),
  CONSTRAINT `formando_ibfk_1`
    FOREIGN KEY (`fk_cc`)
    REFERENCES `form2`.`pessoa` (`cc`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `form2`.`accaoaluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form2`.`accaoaluno` (
  `fk_accao` VARCHAR(10) NOT NULL,
  `fk_formando` INT(11) NOT NULL,
  PRIMARY KEY (`fk_accao`, `fk_formando`),
  INDEX `fk_formando` (`fk_formando` ASC),
  CONSTRAINT `accaoaluno_ibfk_1`
    FOREIGN KEY (`fk_accao`)
    REFERENCES `form2`.`accao` (`cod_accao`),
  CONSTRAINT `accaoaluno_ibfk_2`
    FOREIGN KEY (`fk_formando`)
    REFERENCES `form2`.`formando` (`id_formando`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `form2`.`ufcd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form2`.`ufcd` (
  `ufcd` VARCHAR(4) NOT NULL,
  `ofi_ufcd` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ufcd`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `form2`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form2`.`aula` (
  `id_aula` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_accao` VARCHAR(10) NOT NULL,
  `fk_ufcd` VARCHAR(4) NOT NULL,
  `data_h` DATE NOT NULL,
  `sumario` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_aula`),
  INDEX `fk_ufcd` (`fk_ufcd` ASC),
  INDEX `fk_accao` (`fk_accao` ASC),
  CONSTRAINT `aula_ibfk_1`
    FOREIGN KEY (`fk_ufcd`)
    REFERENCES `form2`.`ufcd` (`ufcd`),
  CONSTRAINT `aula_ibfk_2`
    FOREIGN KEY (`fk_accao`)
    REFERENCES `form2`.`accao` (`cod_accao`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `form2`.`formador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form2`.`formador` (
  `id_formador` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `fk_cc` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_formador`),
  INDEX `fk_cc` (`fk_cc` ASC),
  CONSTRAINT `formador_ibfk_1`
    FOREIGN KEY (`fk_cc`)
    REFERENCES `form2`.`pessoa` (`cc`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `form2`.`faltaformador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form2`.`faltaformador` (
  `fk_formador` INT(11) NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`data`, `fk_formador`),
  INDEX `fk_formador` (`fk_formador` ASC),
  CONSTRAINT `faltaformador_ibfk_1`
    FOREIGN KEY (`fk_formador`)
    REFERENCES `form2`.`formador` (`id_formador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `form2`.`faltaformando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form2`.`faltaformando` (
  `fk_aula` INT(11) NULL DEFAULT NULL,
  `fk_formando` INT(11) NOT NULL,
  `falta` TINYINT(1) NOT NULL,
  `descicao` VARCHAR(200) NULL DEFAULT NULL,
  `justif` TINYINT(1) NULL DEFAULT NULL,
  INDEX `fk_aula` (`fk_aula` ASC),
  INDEX `fk_formando` (`fk_formando` ASC),
  CONSTRAINT `faltaformando_ibfk_1`
    FOREIGN KEY (`fk_aula`)
    REFERENCES `form2`.`aula` (`id_aula`),
  CONSTRAINT `faltaformando_ibfk_2`
    FOREIGN KEY (`fk_formando`)
    REFERENCES `form2`.`formando` (`id_formando`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `form2`.`formadorturma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form2`.`formadorturma` (
  `fk_accao` VARCHAR(10) NOT NULL,
  `fk_formador` INT(11) NOT NULL,
  PRIMARY KEY (`fk_accao`, `fk_formador`),
  INDEX `fk_formador` (`fk_formador` ASC),
  CONSTRAINT `formadorturma_ibfk_1`
    FOREIGN KEY (`fk_accao`)
    REFERENCES `form2`.`accao` (`cod_accao`),
  CONSTRAINT `formadorturma_ibfk_2`
    FOREIGN KEY (`fk_formador`)
    REFERENCES `form2`.`formador` (`id_formador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
